"""Generate configs/races.toml (the versioned race list, PRD FR-1).

Run once; the TOML is the source of truth afterwards. 2022-2024 are taken in
full (ground-effect regulations). 2018-2021 are a hand-picked subset chosen
for circuit diversity plus wet / safety-car / red-flag races, and carry a lower
training weight because the cars and tyres are from a different rule set.
"""
import logging
import tomllib
import unicodedata
from pathlib import Path

import fastf1

logging.getLogger("fastf1").setLevel(logging.ERROR)
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs" / "races.toml"

NAMES = {
    "melbourne": "australia", "sakhir": "bahrain", "shanghai": "china", "baku": "azerbaijan",
    "barcelona": "spain", "monte carlo": "monaco", "monaco": "monaco", "montreal": "canada",
    "le castellet": "france", "spielberg": "austria", "silverstone": "britain",
    "hockenheim": "germany", "budapest": "hungary", "spa-francorchamps": "belgium",
    "monza": "italy", "singapore": "singapore", "marina bay": "singapore", "sochi": "russia",
    "suzuka": "japan", "austin": "usa", "mexico city": "mexico", "sao paulo": "brazil",
    "yas marina": "abu_dhabi", "yas island": "abu_dhabi", "mugello": "tuscany",
    "nurburgring": "eifel", "portimao": "portugal", "imola": "emilia_romagna",
    "istanbul": "turkey", "zandvoort": "netherlands", "lusail": "qatar", "jeddah": "saudi_arabia",
    "miami": "miami", "las vegas": "las_vegas",
}
OVERRIDE = {(2020, 2): "styria", (2020, 5): "70th_anniversary", (2020, 16): "sakhir",
            (2021, 8): "styria", (2021, 9): "austria"}

# Older-season picks: round -> why. Chosen for circuit spread and wet/SC/red-flag content.
OLDER = {
    2018: {1: "Season opener, VSC/SC, Albert Park", 2: "High-degradation desert circuit",
           3: "Safety car + strategy gamble", 4: "Street circuit, multiple SCs, chaos",
           6: "Street circuit, low overtaking", 10: "Lap-1 safety car, mixed conditions",
           11: "Wet: rain mid-race, SC, tyre switches", 13: "Long high-speed circuit",
           15: "Street night race, SC every year", 17: "Suzuka figure-eight",
           20: "Wet-ish, SC, Interlagos"},
    2019: {2: "Safety car swung strategy", 4: "Street circuit, SC", 6: "Monaco",
           7: "Montreal, SC/penalty race", 10: "Silverstone high-speed degradation",
           11: "Wet: rain, multiple SCs, tyre chaos", 14: "Low drag, low deg",
           15: "Street night race", 17: "Suzuka", 18: "Altitude circuit",
           20: "Late SC, dramatic finish"},
    2020: {1: "Season opener, multiple SCs", 4: "Extreme degradation, late tyre blowouts",
           7: "Spa", 8: "Red flag, low-drag", 9: "Red flags, new circuit",
           11: "Cold, low grip, SC", 12: "New circuit, low grip", 13: "Imola return",
           14: "Wet: extremely low grip, inters", 15: "Big crash, red flag + SCs"},
    2021: {1: "Season opener", 2: "Wet start, red flag", 3: "Portimao",
           5: "Monaco", 6: "Baku red flag", 10: "Silverstone sprint-weekend race",
           11: "Wet start, red flag, standing restart", 13: "Zandvoort return",
           15: "Wet finish, late inters call", 16: "Wet: inters vs slicks", 17: "COTA",
           21: "Multiple red flags + SCs, night race"},
}


def slug(s: str) -> str:
    return unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower()


def existing_whys() -> dict:
    if not OUT.exists():
        return {}
    with open(OUT, "rb") as f:
        return {r["race_id"]: r["why"] for r in tomllib.load(f)["races"]}


def main():
    keep = existing_whys()
    lines = ["# Fixed, versioned race list for Overtake (PRD FR-1, NFR 'Reproducibility').",
             "# Generated by scripts/build_race_list.py. Changing this list changes every",
             "# downstream result. race_id = <season>_<short_circuit_name> is the primary key",
             "# in every Parquet table, so never rename an existing id.",
             "#",
             "# 2022-2024: every race (ground-effect era, train_weight 1.0).",
             "# 2018-2021: curated subset, train_weight 0.4 (different cars/tyres/regs).",
             ""]
    n = 0
    for season in range(2018, 2025):
        sched = fastf1.get_event_schedule(season, include_testing=False)
        for r in sched.itertuples():
            rnd = int(r.RoundNumber)
            if season >= 2022:
                why = "Full-season coverage"
                weight, era = 1.0, "ground_effect"
            else:
                if rnd not in OLDER[season]:
                    continue
                why, weight, era = OLDER[season][rnd], 0.4, "pre_2022"
            name = OVERRIDE.get((season, rnd)) or NAMES[slug(r.Location)]
            rid = f"{season}_{name}"
            why = keep.get(rid, why)
            lines += ["[[races]]", f'race_id = "{rid}"', f"season = {season}", f"round = {rnd}",
                      f'era = "{era}"', f"train_weight = {weight}", f'why = "{why}"', ""]
            n += 1
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("races:", n)


if __name__ == "__main__":
    main()
